### ISSUE TITLE
The path for ipa plugins.

### ISSUE THREAD

**Issue by LMQ173** [BepInEx/IPALoaderX#2]
Hi, I'm a user. After several unsuccessful trails, may I ask where should I put the IPA plugins. Does this IPA loader also work for Koikatu?

**Comment by ghorsington** [comment]
Greetings!

As this is a proper IPA emulator, IPA plugins go in the same folder as in the original IPA -- that it `Plugins` folder. Unfortunately the version of IPALoaderX for BepInEx 4 does not create that folder for you, so you have to create it yourself.

I updated the README with this information.

This loader has been tested to work with Koikatu and BepInEx 4.1.1.0.  
*Note:* make sure you download [the original 1.0.0.0 version of IPALoaderX](https://github.com/BepInEx/IPALoaderX/releases/tag/2018-12-23) if you use BepInEx 4. The latest build is only meant for BepInEx 5.

If you have any more questions related to plugins folder, feel free to comment here.  
If you have any new issues, please make a new issue.

**Comment by LMQ173** [comment]
Thank you. The 1.0.0.0 version IPALoaderX now works well with my Koikatu. Could you consider add the "BepInEX\IPA\" as an alternative folder to store the plugins? I think it's better to make the game path as clean as possible, and makes it more compatible, since many downloaded Koikatu plugins use that path as default.

By the way, I found this version crashes with HoneySelect, even after I reinstalled the game. I attached the logs here.
[output_log.txt](https://github.com/BepInEx/IPALoaderX/files/3017514/output_log.txt)
[error.log](https://github.com/BepInEx/IPALoaderX/files/3017515/error.log)

**Comment by ghorsington** [comment]
Sure, I'll add an option to change plugins path. However, it won't be available for use in BepInEx 4, as the new IPALoaderX has been rewritten for BepInEx 5 that is not yet released (and is only available as bleeding edge builds).

As for the crash, you need to reconfigure BepInEx entrypoint in the configuration in order to get it working with HoneySelect.  

In `BepInEx/config.ini` change
```ini
entrypoint-assembly=UnityEngine.dll
entrypoint-type=Application
entrypoint-method=.cctor
```
to
```ini
entrypoint-assembly=UnityEngine.dll
entrypoint-type=MonoBehaviour
entrypoint-method=.cctor
```

You might also want to enable the console by setting `console=true` so you can see any other possible errors.
